spring:
  profiles:
    group:
      local: localDB, jasypt, oauth, mybatis, aws
      prod: prodDB, jasypt, oauth, mybatis, aws
      test: testDB, jasypt, oauth, mybatis, aws
    active: local

  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 10MB
